# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bbfd0990d9f26acf028f09f0527a8217292b328370bf9c89999b2fb5ae76deb95f37eb0dbf8b68a3dc8b435cd81ea7dcf5c9bbf2fa63b2fc51300cb8fab1737

test:
  secret_key_base: 4d10c3e3e37302e09d702afa13f8c579fd616d62bb752d20df5ba0f18fcef01ba3525868d9a4778edca16ae7691c97fbd5896e56d6477214722f5ab8409d2284

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
